### ISSUE TITLE
Support viewPager2

### ISSUE THREAD

**Issue by maulik9898** [TOrnelas/SegmentedProgressBar#11]
Any plan to add support for viewpager2 . It would be great if this library support viewpager2 out of the box

**Comment by TOrnelas** [comment]
Hey @maulik9898 that is actually the only viewpager the library supports: https://github.com/TOrnelas/SegmentedProgressBar/blob/master/segmentedprogressbar/build.gradle#L31

**Comment by TOrnelas** [comment]
I have [updated the readme file](https://github.com/TOrnelas/SegmentedProgressBar/commit/2d0df6f89b906f4e45c51a2443d6840cacb8f64d) to avoid future confusion on this.

**Comment by iscomad** [comment]
I think, you are missing something here.
The ViewPager2 library is fetched, but is not used in your project. The imported ViewPager in SegmentedProgressBar is the old one. Could you check it again, please?
